services:
  - type: web
    name: apex-docs-web
    runtime: python
    env: production
    plan: free
    region: oregon
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: apex-docs-db
          property: connectionString

databases:
  - name: apex-docs-db
    plan: free