# .github/workflows/ci.yml
name: CI Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Run simple app test (check if app starts)
      - name: Test app import
        run: |
          python -c "from app import app; print('App imported successfully')"
      
      # 5. Optional: Run unit tests
      # - name: Run tests
      #   run: python -m unittest discover tests/

      # 6. Success!
      - name: Notify success
        run: echo "✅ CI passed! Code is ready to deploy."